repos:
  - repo: local
    hooks:
      - id: go-fmt
        name: go-fmt
        entry: gofmt
        language: system
        args: ['-w', '-s']
        files: '\.go$'
      
      - id: go-imports
        name: go-imports
        entry: goimports
        language: system
        args: ['-w', '-local', 'github.com/nashabanov/ueba-event-generator']
        files: '\.go$'
      
      - id: go-vet
        name: go-vet
        entry: go vet
        language: system
        args: ['./...']
        files: '\.go$'
        pass_filenames: false
      
      - id: go-test
        name: go-test
        entry: go test
        language: system
        args: ['-v', './...']
        files: '\.go$'
        pass_filenames: false
