generator:
  name: "production-generator"
  events_per_second: 1000
  event_types: ["netflow", "syslog"]
  event_config:
    netflow:
      version: 9
      source_ips:
        - "10.0.0.0/8"
        - "172.16.0.0/12"
        - "192.168.0.0/16"
      dest_ips:
        - "8.8.8.8"
        - "1.1.1.1"
        - "208.67.222.222"
      ports: [80, 443, 53, 22, 25, 110, 995, 993, 143, 587, 8080, 8443, 3306, 5432, 6379]
      protocols: ["TCP", "UDP"]
    syslog:
      facility: 16
      severity: 6
      hostnames:
        - "prod-web-01"
        - "prod-web-02"
        - "prod-db-01"
        - "prod-cache-01"
        - "prod-lb-01"
      programs:
        - "nginx"
        - "mysql"
        - "redis"
        - "haproxy"
        - "kernel"

sender:
  name: "production-sender"
  protocol: "tcp"
  destinations:
    - "siem-collector-01:514"
    - "siem-collector-02:514"
    - "backup-collector:514"
  retries: 5
  timeout: "30s"

pipeline:
  buffer_size: 2000
  worker_count: 4

logging:
  level: "warn"
  format: "json"
  file: "/var/log/ueba-generator.log"
